### ISSUE TITLE
Aurelia CLI plugin skeleton + Typescrip 3+

### ISSUE THREAD

**Issue by HamedFathi** [aurelia-contrib/aurelia-getting-started#32]
@huochunpeng 

May I ask you to share a repository based on your `how-to-use-cli-to-develop-plugin` with Aurelia CLI 1.0 + Typescript **3+**?

You have a repository sample for Javascript but not for Typescript. I tried but many problems occurred.

**Comment by huochunpeng** [comment]
Sure. Will do.

What are your problems?

**Comment by huochunpeng** [comment]
https://github.com/huochunpeng/demo-plugin-cli-ts

**Comment by HamedFathi** [comment]
@huochunpeng 

I transfer your plugin files to a new project that is made with Aurelia CLI + webpack + ts but I have problem

This is the repository. [AuPluginTest](https://github.com/HamedFathi/AuPluginTest)
I want to have nested folder for each plugins.

![image](https://user-images.githubusercontent.com/8418700/48580928-b68c8100-e935-11e8-952e-e8c73295426e.png)

![image](https://user-images.githubusercontent.com/8418700/48581079-108d4680-e936-11e8-8ec9-8b7672e54b40.png)

Do you know what is wong?

**Comment by huochunpeng** [comment]
`config.globalResources([PLATFORM.moduleName('./demo/index')])` would not work.

`./demo/index` is an entry, not an Aurelia resource (element/value-converter/...).

Try
```ts
import {FrameworkConfiguration} from 'aurelia-framework';
import {PLATFORM} from 'aurelia-pal';
import demo from './demo/index';

export function configure(config: FrameworkConfiguration) {
  demo.configure(config);
}
```

I think you did something like this for aurelia-toolbelt.

**Comment by HamedFathi** [comment]
@huochunpeng 

> I think you did something like this for aurelia-toolbelt.

Yes, Now your structure is different. 

Unfortunately, I tried but the problem exists, so sorry, May I ask you to make PR to the [AuPluginTest](https://github.com/HamedFathi/AuPluginTest)?

Aurelia-Toolbelt works with `Fusebox` but I need to use `Webpack` for their [Webpack Bundle Analyzer
](https://www.npmjs.com/package/webpack-bundle-analyzer).

Your structure helps me to achieve this.

**Comment by huochunpeng** [comment]
Ok, I will have a look.

**Comment by huochunpeng** [comment]
You probably need a fork of the project anyway to support vnext.

The idea should still work, just use gulp-typescript to transpile a folder to dist.

We have not done anything in cli to support vnext yet. It wouldn’t be much change in cli. Vnext is easier for any bundler.

**Comment by HamedFathi** [comment]
Thanks for your help

I updated the skeleton [here](https://github.com/HamedFathi/Aurelia-Plugin-Skeleton-Webpack)

1. Support SCSS for plugins
2. Support other build types (System, ES2015, AMD)
